# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Названия товара ')),
                ('alias', models.SlugField(verbose_name='alias  категории')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Названия товара ')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('image', models.CharField(max_length=255, verbose_name='Ссылка на картинку ')),
                ('alias', models.SlugField(verbose_name='alias  категории')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
            ],
        ),
    ]
