# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160517_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('familiy_name', models.CharField(max_length=55)),
                ('number', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=55)),
                ('country', models.CharField(max_length=55)),
                ('city', models.CharField(max_length=55)),
                ('adress', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Категория '),
        ),
        migrations.AlterField(
            model_name='item',
            name='alias',
            field=models.SlugField(verbose_name='alias  категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(max_length=255, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Названия товара'),
        ),
    ]
