# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160530_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='item/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
