# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160530_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='item', verbose_name='Фото'),
        ),
    ]
