BBBB BBBBBBBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
	XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
	XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
    XXXXXXX XX XX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
  XXXX  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBXXXXXXXXXXX XXX
	XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
	XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXX XBBBBBB BBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXX
    XXXXXXX XXXX XBBBBBB BBBBBBBBBBBBBBBBBXX XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXX
    X
    	XXXXXXXXXXXX
    	XXXXXXXXXXXX
    X
    XXXXX
    X
    	XXXXXXXXXXXX XXXX
    	XXXXXXXXXXXX
    X
    XXXXXXXX
XXXXXXXXXXXXXXXXXXX

XXXXXX
		XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXX
							XXX XXXXXXXXXX XXXXXXXXXXX
								XXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XX XX XX XX XXXXXXXXXXXX
								XXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
							XXXXX
						XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XX XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXX
					XXXX XXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
							XXX XXXXXXXXXX XXXXXXXXXXXX

								XXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
								XXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX

								XXXX XXXXXXXXXXXXXXXXXX
								XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXX
									XXX
									XXXXX XXXXXXXXXXXXXXXXXXXXX
								XXXXXXXXX
								XXX XXXXXXXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXX
								XXXXX
							XXXXXX

							XXXXX
						XXXXXX
					XXXXXX
			XXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXX

	XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


		XXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXX
						BBB BBBBB BB BBBBBB
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXX XX
									XXXX XXXXXXXXXXXXXXXXXXXXXXX X
									XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
										XXXX  XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XX
										XXX XXXXX XXXXXXXXXXXXXXXXXXX
										XX XXXXXXXXXXXXXXXXX
										XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXXXXXXX XX
										XXXXXXX XX XXXXXXXX
									XXXXXX


								XXXXXX
							XXXXXX
				BBBBBB
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
				XX XXXXX XXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXX
			XXXXXX
	XXXXXXXXXX




	XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXX X
				XXXX XXXXXXXXXXXX
					XX XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX XXXXXXXX X XXX X XXX XXXXXX XXXXXXXXXXXXX
					XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
				XXXXXX
			XXXXXX
		XXXXXX
	XXXXXXXXX



XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXX
	XXX XXXX X XXXXXXXXXXXXXXXXX
		XX XXXXXXXX
			XXXX XXXXXX
		X
		XXX XXXXX X XXXXXXXXXX X XXXXXXXXXXXXXXXXX X XX X
		XXX XXXXXXXXX
		XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
			XXXXXX X XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
		XXX
		XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX

	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


		XXX XXX X XXXXXXXXXXXXXXXXX
		XX XXXXXXX
			XXX XXXXXX
		X
		XXX XXXX X XXXXXXXXXXXXXXXXX
		XXXXXXXXXXX
			XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
			XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX
		XXX XXXXX X XX
		XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX
			XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
			XXXXX X XXXXX X XXXXXXXXX XXXXXXXXXXXX XX
		XXX
		XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
	XXX

XXX
 XXXXXXXXXXXXXXXXXXXXXXXXXXXX X

   XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXX
   XXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
   XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX

   XX XXXXXXXXXX X XXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXX X XXXXXXXXX X X XXXXXX
   X
  XXX
XXXXXXXXX
XXXXXXX
XXXXXXX