XXXXXXX XXXX XBBBBBB BBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXX


XXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XX XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
	XX XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXX XXXX X XXXXXXXXXXXXXXXXX
		XX XXXXXXXX
			XXXX XXXXXX
		X
		XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
			XXXXXX X XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXX
		XXXXXXXX XXXXXXXXXXXXXXXXXXXXX

		XXX XXX X XXXXXXXXXXXXXXXXX
		XX XXXXXXX
			XXX XXXXXX
		X
		XXX XXXX XXXXXXXXXXXXXXXXXX
		XXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX
		XXX XXXXX X XX
		XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
			XXXXX X XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
		XX
		XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
	XXX

XXX
XXXXXXXXX