BBBB BBBBBBBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX 
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
	XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
	XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
    XXXXXXX XX XX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX       
    XXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXX
    X
    	XXXXXXXXXXXX
    	XXXXXX XXXXXX
XXXXXXXXXXXX XXXX
XXXXXXXX XXXXXX	
XXXXXXXXXXXX XXXXXX XXXXXXXXXXX
    X
    XXXXXXXX
XXXXXXXXXXXXXXXXXXX

XXXXXX
	XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXX
							XXX XXXXXXXXXX XXXXXXXXXXX
								XXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XX XX XX XX XXXXXXXXXXXX
								XXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
							XXXXX
						XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
							XXX XXXXXXXXXX XXXXXXXXXXXX
								XXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
								XXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
							
								XXXX XXXXXXXXXXXXXXXXXX
								XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXX
									XXX
									XXXXX XXXXXXXXXXXXXXXXXXXXX
								XXXXXXXXX
								XXX XXXXXXXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXX
								XXXXX
							XXXXXX
							
							XXXXX
						XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
							
							
						XXXXXX
				XXXXXX
			XXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXX
	
	
		XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXX
							XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
								XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
								XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
								XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
								XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
							XXXXXXXXX
						XXXXXX
						XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
							XXX XXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
								XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
								XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                                    XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
										XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX 
										XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
										XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
										XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
                                    XXXXX
                                XXXXX 
							XXXXX
						XXXXXX
					XXXXXX
				XXXXXX
			XXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXX

	 XXXXXXXXXXXXXXXXXXX

	XXXXXXXX XXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXX
			XXXXXX
			XXX XX
				XXXX XXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXX   XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
			
								XX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX
							XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
					XXXXXX
				XXXXXX
			XXXXXX

		XXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXX

	XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
	
		
		XXXX XXXXXXXXXXXXXXXXXXXXXX
			
		XXXXXX
		
		XXXX XXXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXX
					XX XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX XXXXXXXX X XXX X XXX XXXXXX XXXXXXXXXXXXX
					XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
				XXXXXX
			XXXXXX
		XXXXXX
		
	XXXXXXXXX

	
	XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBXXXXXXXXXXX
	XXXXXXX XXXX XBBBBBB BBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXX
	XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
	XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXX
	XXX XXXX X XXXXXXXXXXXXXXXXX
		XXX XXXXX X XXXXXXXXXX X XXXXXXXXXXXXXXXXX X XX X
		XXX XXXXXXXXX
		XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXX  XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX  XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX       XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX X XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
		XXX
		XXXXXX XXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXX XXX X XXXXXXXXXXXXXXXXX
				XX XXXXXXX
					XXX XXXXXX
					X
		XXX XXXX X XXXXXXXXXXXXXXXXX
		XXX XXXXXXX X XXXXX
		XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXX

		 XXXX
		 		XXXXX XX XXXXXX 
		  XXX XXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX X 
                X
                	XXXXXXXXXXXXXXXXXXX
                XXXXXXXX XXXXXXXXXXXXXXXX X X X X XXX XX XXXXXXXXXXXXXXX X X   XX XXXXXXXXXXXXXX X X XXX
            	XXXX
          		X
          X
		XXXXXX X XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXX XXXXXXXXXXXXXXXXXXXXX X
				XXXXXXXXXXXXXXXXXXXXXXXXXX
			
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX

		XXX
XXX
XXXXXXXXX
XXXXXXX
XXXXXXX