BBBB BBBBBBBBBBB
BBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX  
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXX

    XXXXXXX gettext('Souvenir 4 You') XXXXXXXX
	XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
	XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
	XXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
	
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX

    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX

    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
   
	XXXXXX XXXXXXXXXXXXXXXX
		XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXX
		XXXXXXXXXXXX 
		XXXXXXXXXXXX
		XXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXX XXXXX
		XXXXXXXXXXXXXXXXXXX XXXXX
		XXXXXXXXXXX
		X
		XXXXXXXXXXX
		X
		XXXXXXXXXX XXXXX XXXXX
		XXXXXXXXXXX XXX XXXX XXXX XXXXXX
		X
	XXXXXXXX
XXXXXXX

XXXXXX
   XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X
       XXXX XXXXXXXXXXXXXXXXX  X
        XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX
		XXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXX XXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext('Home') XXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXX gettext('Info') XXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX
              XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXX XXXXXXXXX X XXXXXXXXXX
                XXXXXX XXXXXXXXX gettext('German') XXXXXXXXX
                XXXXXX XXXXXXXXXXXX gettext('Russian') XXXXXXXXX
              XXXXX
            XXXXX
          XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX XXX
      XXXXXX
    XXXXXX

   XXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XX
       XXXX XXXXXX XXX
    XXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX BBBBBB BBBBBBBBBBBBBBBBBBBBBBXX
		XXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX
		XXXXXXXXX
    XXXXXXXXX

    XXXX XXXXX XXX
    XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
           XXXX XXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXX

			XXXXXX
            XXXX XXXXX XXX
        XXXXXX
        XXXX XXXXXXXXXXX XXX
    XXXXXXXXXX




    XXXX XXXXXXXX XXX
    XXXX XXX XXXXXX XXXXX XXX XXXX XXXXXXXXX XXXXXXX XXXX XXXXXXXX XXX XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXXXXXX  XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X XXXXX XX
            BBB BBBBBBBB BB BBBBBBBBBB
                        XXXX XXXXXXXXXXXX X
                            XXXX XXXXXXXXXXXXXXXXXXXX X
                                XXXXX XXXXXXXXXXXXXXX XXXXXX  XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                            XXXXXXX
                                XXXX
                                    XXXXXXXXXXXXXXXXX
                                XXXXX
                                XXXXXXXXXXXXXX XXXX XXXXXXXXX XXX XXXX XX XXXXXXXX XXXX
                                XX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
                            XXXXXX
                        XXXXXX
            BBBBBB
        XXXXXX
    XXXXXXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXX


    XXXX XXXXXXXXX XXX

    XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX XXXX XXXX XXXXXXXXXXXXXXXXX X
        XXXX XXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXX

			XXXXXX
            XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXX XXXXXX XXXXX XXX

		XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
		XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
		XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
		XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX


		XXXX XXX XXXXXX XXX

		XXXX XXXXXXXXXXXX

			XXXX XXXXXXXXXXXXXX

				XXXX XXXXXXXXXXXXXX

					XXXXXXXXX
						XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX X XXXXX XXXXX XXXXXXXX XXXXXX XXX XXXXX XXXXXXXX XX XXX XXXXX XXXX XXX XXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
					XXXXXXXXXX

					XXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
						XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
					XXXXXXXXXX

					XXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXX XXXX XX XXXX XXXXX XXXXXX XXXXXXX XXXX XXXXXXX XXXXXX XX XXXXXXXXXXXXX
						XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
					XXXXXXXXXX


				XXXXXX XXXX XXXXXX XXX

			XXXXXX XXXX XXXXXXXXX XXX

		XXXXXX XXXX XXXXXXX XXX


		XXXX XXXXXXXX XXX XXXXXX XXXXX XXXXXXX XXX

		XXXX XXXXXXXXXXXXXX

			XXXXXX XXXXXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXXXXXXXXXXXXXXXXX

		XXXXXX XXXX XXXXXXXXX XXX

		XXXX XXXXXXXXXXXX

			XXXXXX XXXXXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXXXXXXXXXXXXXXXXX

		XXXXXX XXXX XXXXXXX XXX


	XXXXXXXXXX
            XXXX XXXXX XXX
        XXXXXX
        XXXX XXXXXXXXXXX XXX
    XXXXXXXXXX


    XXXX XXXX XX XXXXXX XXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXX XXX
    XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXX X
	XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXX
	  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXX X X
      XXXXXXXXXXXXXX X XXXXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXXX XXX
      XXXXXXXXXXXXXX X XXXXXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXXX XXX
      XXXXXXXXXXXXXX X XXXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXXX XXX
    XX

    XXX XXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXX XXX
      XXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
      XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX

    XXX XXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXX

    XXX XXXXXXX XX

    XXX XX X XX X X XXXXXXXXXXXXXXXXX XXXX X
      XXXXXX X XXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXX
      XXX

      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XX X
        XXXXXX XXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXX XXXXXXXX
        X
      XXXXXXXXXX XXXX
    X
  XXXXXXXXX
  XXXXXX
        XXXXXXXXXX
	XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX X
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXX

			XXXXXX
				    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X X XXXXXXXXXXXXX X X XXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXX XX X XXXX XX XXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXX
                        XXX XXX XXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXX XXX XXX XXX XXX XXXXXXXXXXXXXX
                    XXXXX
                    XXXX
                    XXX XXXXXXXXXXXXXXXXXXXX
                        XXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                        XXXXX
                        XXXX
							XX XXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
					  XXXXX
                    XXXXX
                    XXX XXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
      XXXXXX
	XXXXXXXXXX


	XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
	XXXXXXXXXX
    XXXX XXXXXX XXX
    XXXXXXX XXXXXBBBBBB  BBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXXX
    XX XXXXXXX XX XXX XXXXXXXX XXXX XXXX XX XXX XXXX
     XXXXXXXX XXXXXXXXXXX X
  XXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
     XXX XXXXXX X XXXXXXXXXXXXX
	  XXXXXX X XXXXXXXXXXXXX X XXXXXX X XXXXXXXXXX X XXXXXXXXXXXXXXXXXX X XXXXX

	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
	XX XXXXXXXXXXXXXXX
	X
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXXXX X XX
    XX XXXXXX
    XXXXXX XXXXXX
  X
  XXX
  XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
X
XXXXXXXXXXXX
  XXXXXXXXX
XXXXXXX
XXXXXXX